version: '3'
services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"